title: Guobin Zhao's Homepage
page-top-title: 墨染不想回首
top-section-bg-text: Chemical Engineering
home-subtitle: Guobin Zhao&ensp;|&ensp;赵国斌
copyright-text: '&copy; ZHAOGUOBIN 2024. All Rights Reserved.'
